language: cpp

compiler: g

sudo: require

service:
  - docker

git:
  depth: false

env:
  global:
    # Job parallelization for Makefile
    - MAKEFLAGS="-j 2"

# Notifications
notifications:
  email:
    recipients:
    - florent.poinsard@epitech.eu
    - cecile.cadoul@epitech.eu
    - julien.ollivier@epitech.eu
    on_success: never
    on_failure: always
  slack:
    rooms:
      - epitech-tls-22:4QoGtulORMzh9mU0ugBYrTT8
    template:
      - "Build %{repository_slug}@%{branch} by %(author} %{result} in %{duration}"

# Job declaration
jobs:
    include :
        # Build check phase
        - stage: build
          # Run simple build
          name: "Build"
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - chmod +x ./ci/script/*.sh
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && ./ci/script/build.sh"

        # All the testing phase
        - stage: tests
          # Run unit tests
          name: "Unit Tests"
          install:
            - docker pull epitechcontent/epitest-docker
          script:
            - chmod +x ./ci/script/*.sh
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && ./ci/script/unit_test.sh"
        -
          # Run functional tests
          name: "Functional Tests"
          before_script:
            - docker pull epitechcontent/epitest-docker
          script:
            - chmod +x ./ci/script/*.sh
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && ./ci/script/functional_test.sh"

        # Production deployement
        - stage: deploy-production
          # Deploy to epitech production branch
          name: "Deployement Epitech Server"
          if: branch IN (master, travis) AND type != cron AND type != pull_request
          script:
            - chmod +x ./ci/script/*.sh
            - ./ci/script/deploy_epitech.sh
        -
        
          # Deploy the documentation through github pages
          name: "Deployement Documentation"
          if: branch IN (master) AND type != cron AND type != pull_request
          before_script:
            - docker pull epitechcontent/epitest-docker
          script:
            - chmod +x ./ci/script/*.sh
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && ./ci/script/deploy_documentation.sh"
          deploy:
            provider: pages
            skip_cleanup: true
            github_token: $GITHUB_TOKEN
            keep_history: true
            verbose: true
            on:
              branch: master

        # Pre production deployement
        - stage: deploy-pre-prod
          # Deploy on epitech pre production branch
          name: "Deployement Epitech Server pre-prod"
          if: branch IN (dev) AND type != cron AND type != pull_request
          script:
            - chmod +x ./ci/script/*.sh
            - ./ci/script/deploy_epitech_pre_prod.sh
